/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI.PaymentManagerWorkArea;

import Business.CommerceSystem;
import Business.Roles.FinanceEnt.CreditPaymentOrg.CreditPaymentOrg;
import Business.Roles.FinanceEnt.CreditPaymentOrg.PaymentManager;
import Business.Roles.Role;
import Business.UserAccount.UserAccount;
import UI.WorkArea;
import java.awt.Color;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author sichengzhou
 */
public class PaymentManagerAreaJPanel extends WorkArea {

    PaymentManager paymentManager;

    /**
     * Creates new form PaymentManagerAreaJPanel
     */
    public PaymentManagerAreaJPanel(UserAccount account, CommerceSystem business, Role role) {
        super(account, business, role);
        initComponents();
        this.setBackground(Color.yellow);
        this.paymentManager = (PaymentManager) role;
        refreshTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        JTableCreditPayment = new javax.swing.JTable();
        enterpriseLabel1 = new javax.swing.JLabel();

        JTableCreditPayment.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Name", "Price"
            }
        ));
        jScrollPane1.setViewportView(JTableCreditPayment);

        enterpriseLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        enterpriseLabel1.setText("Credit Payment Panel");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 548, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(enterpriseLabel1))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(enterpriseLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(43, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void refreshTable() {
        ArrayList<CreditPaymentOrg.SinglePaymentInfo> paymentInfos = this.paymentManager.getCreditPaymentOrg().getPaymentInfos();
        int tableColumnNum = paymentInfos.size();
        Object ColNames[] = {"PaymentInfo", "Amount", "FromOrg", "Time"};
        Object rowDataItems[][] = new Object[tableColumnNum][ColNames.length];
        for (int idx = 0; idx < tableColumnNum; idx++) {
            rowDataItems[idx][0] = paymentInfos.get(idx).getInfo(); // PaymentInfo
            rowDataItems[idx][1] = paymentInfos.get(idx).getAmount(); // Amount
            rowDataItems[idx][2] = paymentInfos.get(idx).getUserOrg(); // FromOrg
            rowDataItems[idx][3] = paymentInfos.get(idx).getTime(); // Time;
        }

        this.JTableCreditPayment.setModel(new DefaultTableModel(rowDataItems, ColNames) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        }
        );

    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable JTableCreditPayment;
    private javax.swing.JLabel enterpriseLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
