/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI.ProductManagerWorkArea;

import Business.CommerceSystem;
import Business.Order.DeliverItem;
import Business.Roles.DeliveryEnt.DeliveryEnt;
import Business.Roles.Role;
import Business.Roles.FactoryEnt.ProductOrg.ProductManager;
import Business.Roles.FactoryEnt.ProductOrg.ProductOrg;
import Business.Roles.InDeliverOrganization;
import Business.UserAccount.UserAccount;
import UI.WorkArea;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author sichengzhou
 */
public class ProductManagerAreaJPanel extends WorkArea {

    ProductManager productManager;
    ProductOrg productOrg;
    DeliveryEnt selectedDeliveryEnt;

    /**
     * Creates new form ProductManagerAreaJPanel
     */
    public ProductManagerAreaJPanel(UserAccount account, CommerceSystem business, Role role) {
        super(account, business, role);
        this.productManager = (ProductManager) role;
        this.productOrg = this.productManager.getProductOrg();
        DefaultComboBoxModel deliveryComboBoxModel = new DefaultComboBoxModel();
        this.jComboBox1.setModel(deliveryComboBoxModel);
        this.selectedDeliveryEnt = (DeliveryEnt) this.jComboBox1.getSelectedItem();
        initComponents();
        refreshJTableRequest();
        refreshJTableDelivery();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        enterpriseLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableRequest = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableDelivery = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButton3 = new javax.swing.JButton();

        enterpriseLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        enterpriseLabel1.setText("Product Manager Panel");

        jTableRequest.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableRequest);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("InStock Request:");

        jTableDelivery.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTableDelivery);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Delivery:");

        jButton1.setText("Accept and Send");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Test");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jButton3.setText("Send by");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(enterpriseLabel1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 514, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(18, 18, 18)
                        .addComponent(jButton1))
                    .addComponent(jLabel2)
                    .addComponent(jScrollPane2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(112, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(enterpriseLabel1)
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addGap(18, 18, 18)
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int selectedIdx = this.jTableRequest.getSelectedRow();
        if (selectedIdx == -1) {
            return;
        }
        ProductOrg.RequestFactoryItem requestFactoryItem = this.productOrg.getRequestHandleList().get(selectedIdx);
        ArrayList<DeliverItem> deliverItems = this.productOrg.getRelatedDeliverItems();
        String name = requestFactoryItem.getSmi().getName();
        int number = requestFactoryItem.getNumber();
        InDeliverOrganization fromOrg = this.productOrg;
        InDeliverOrganization toOrg = requestFactoryItem.getWarehouseOrg();
        this.productOrg.getRequestHandleList().remove(selectedIdx);
        this.productOrg.addDeliveryItem(name, null, null, number, fromOrg, toOrg);
        this.refreshJTableDelivery();
        this.refreshJTableRequest();
        // Log
        System.out.println("Accept the request from warehouse organization");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        int selectedRow = this.jTableDelivery.getSelectedRow();
        if (selectedRow == -1) {
            return;
        }
        this.productOrg.setDeliveredForTest(selectedRow);
        refreshJTableDelivery();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        int selectedRow = this.jTableDelivery.getSelectedRow();
        if (selectedRow == -1) {
            return;
        }
//        this.productOrg.getRelatedDeliverItems().get(selectedRow).getAdditionalInfo().setDeliveryEnt(selectedDeliveryEnt);
        ///////////////////////////////

        // Log
        System.out.printf("Process the order \n");
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
        this.selectedDeliveryEnt = (DeliveryEnt) this.jComboBox1.getSelectedItem();
    }//GEN-LAST:event_jComboBox1ActionPerformed
    private void refreshJTableRequest() {
        ArrayList<ProductOrg.RequestFactoryItem> requestHandleList = this.productOrg.getRequestHandleList();
        int tableColumnNum = requestHandleList.size();
        Object ColNames[] = {"ItemName", "InStockPrice", "NeedNumber", "ToOrganization"};
        Object rowDataItems[][] = new Object[tableColumnNum][ColNames.length];
        for (int idx = 0; idx < tableColumnNum; idx++) {
            rowDataItems[idx][0] = requestHandleList.get(idx).getSmi().getName(); // Name;
            rowDataItems[idx][1] = requestHandleList.get(idx).getSmi().getInPrice(); // InStock Price;
            rowDataItems[idx][2] = requestHandleList.get(idx).getNumber(); // Need Number;
            rowDataItems[idx][3] = requestHandleList.get(idx).getWarehouseOrg(); // To which Organization;
        }
        this.jTableRequest.setModel(new DefaultTableModel(rowDataItems, ColNames) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        }
        );
    }

    private void refreshJTableDelivery() {
        ArrayList<DeliverItem> deliverItems = this.productOrg.getRelatedDeliverItems();
        int tableColumnNum = deliverItems.size();
        Object ColNames[] = {"Name", "FromOrganization", "ToOrganization", " Status", "DeliveryOrderNum"};
        Object rowDataItems[][] = new Object[tableColumnNum][ColNames.length];
        for (int idx = 0; idx < tableColumnNum; idx++) {
            rowDataItems[idx][0] = deliverItems.get(idx).getName(); // Name
            rowDataItems[idx][1] = deliverItems.get(idx).getAdditionalInfo().getFromOrg(); // From which Org
            rowDataItems[idx][2] = deliverItems.get(idx).getAdditionalInfo().getToOrg(); // To which Org
            rowDataItems[idx][3] = deliverItems.get(idx).getCurrentStatus();
            rowDataItems[idx][4] = deliverItems.get(idx).getDeliveryOrderNum() != -1 ? deliverItems.get(idx).getDeliveryOrderNum() : "NotAvaNow";
//            rowDataItems[idx][4] = deliverItems
        }
        this.jTableDelivery.setModel(new DefaultTableModel(rowDataItems, ColNames) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        }
        );

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel enterpriseLabel1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableDelivery;
    private javax.swing.JTable jTableRequest;
    // End of variables declaration//GEN-END:variables
}
