package UI.ShopManagerWorkArea;

import Business.CommerceSystem;
import Business.Roles.Role;
import Business.Roles.SaleEnt.ShopOrg.ShopManager;
import Business.UserAccount.UserAccount;
import UI.WorkArea;
import java.awt.CardLayout;
import java.awt.Color;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author raunak
 */
public class ShopManagerAreaJPanel extends WorkArea {

    private ShopManager shopManager;

    /**
     * Creates new form AdminWorkAreaJPanel
     */
    public ShopManagerAreaJPanel(UserAccount account, CommerceSystem business, Role role) {
        super(account, business, role);
        this.setBackground(Color.PINK);
        this.shopManager = (ShopManager) role;
        initComponents();
//        this.jTextField1.setText(restAdmin.getRestaurantName());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        manageMenuJButton = new javax.swing.JButton();
        manageOrdersJButton = new javax.swing.JButton();
        enterpriseLabel1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        manageMenuJButton.setText("Manage Sale Items");
        manageMenuJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageMenuJButtonActionPerformed(evt);
            }
        });

        manageOrdersJButton.setText("Manage Orders Send");
        manageOrdersJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageOrdersJButtonActionPerformed(evt);
            }
        });

        enterpriseLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        enterpriseLabel1.setText("Shop Manager Panel");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Shop:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(enterpriseLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(manageMenuJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(manageOrdersJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(508, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(enterpriseLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(manageOrdersJButton)
                        .addGap(18, 18, 18)
                        .addComponent(manageMenuJButton)))
                .addContainerGap(327, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void manageMenuJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageMenuJButtonActionPerformed
        //
        JDialog jdl = new JDialog();
        jdl.add(new ManageSaleItemsJPanel(this.shopManager));
        jdl.setSize(800, 600);
        jdl.setModal(true);
        jdl.setLocationRelativeTo(null);
        jdl.setVisible(true);
    }//GEN-LAST:event_manageMenuJButtonActionPerformed

    private void manageOrdersJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageOrdersJButtonActionPerformed
        // Manage Orders
        JDialog jdl = new JDialog();
        jdl.add(new ManageOrdersJPanel(this.shopManager.getShopOrganization().getOrdersInShop(), super.business));
        jdl.setSize(800, 600);
        jdl.setModal(true);
        jdl.setLocationRelativeTo(null);
        jdl.setVisible(true);
    }//GEN-LAST:event_manageOrdersJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel enterpriseLabel1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton manageMenuJButton;
    private javax.swing.JButton manageOrdersJButton;
    // End of variables declaration//GEN-END:variables

}
